language: emacs-lisp

sudo: false
cache: bundler

env:
  global:
    - PATH=$HOME/.cask/bin:$PATH

matrix:
  include:
    - env: EMACS=emacs24
      addons:
        apt:
          sources:
            - cassou-emacs
          packages:
            - emacs24
            - emacs24-el

before_install:
  - curl -fsSkL --max-time 10 --retry 10 --retry-delay 10 https://raw.github.com/cask/cask/master/go | python
  - cask install

script:
  cask exec ert-runner
